### ISSUE TITLE
submit buttons on /profile/delete page don't do anything

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#293] opened 2017-10-10 00:29 UTC
Clicking on either the "Cancel and go back" or "Delete my account" button doesn't seem to do anything - no console errors, no network traffic.

**Comment by iandees** [comment] 2017-10-15 14:43
Dupe of #384.

**Closed by iandees** 2017-10-15 14:43 UTC
Labels: bug, priority, qa requested

**Comment by engerm** [comment] 2017-10-15 22:22
Both the "Cancel and go back" or "Delete my account" buttons work.
