### ISSUE TITLE
Use dummy data in admin views of email rather than querying the db

### ISSUE THREAD

**Issue by kcaffall** [RagtagOpen/nomad#604] opened 2018-08-16 18:02 UTC
All email previews on the demo site are throwing a 500 server error.

One example:
https://nomad-demo.ragtag.org/admin/emailpreview/admin_destination_deleted

**Comment by dryan** [comment] 2018-08-16 20:26
https://sentry.ragtag.org/ragtag/nomad-demo/issues/84/ has the error report. Anyone who needs access to it just let me know.

**Comment by dryan** [comment] 2018-08-16 22:12
This is caused by a new install not having any carpools entered. Should we have a dummy object to pass in to the template rather than fetching one from the database?

**Comment by jillh510** [comment] 2018-08-20 21:18
Dup of #608 , closing.

**Comment by kcaffall** [comment] 2018-08-20 22:09
@jillh510 , @iandees  - I disagree. This is not a dupe of #608. The solution for #608 is to query the first ride request in the db. Per @dryan comment here: do we want to have a dummy object to pass into the template rather than fetching one from the db. If that's not necessary, then I'm in agreement with closing this one.

**Comment by iandees** [comment] 2018-08-20 22:13
If we want to do that, we should file a separate ticket or rename/update the description on this one.

**Comment by jillh510** [comment] 2018-08-20 22:18
never mind, filing a new bug

**Closed by jillh510** 2018-08-20 22:18 UTC
Labels: awaiting feedback, bug
