### ISSUE TITLE
Admin > Destinations - unsure where there is a hidden column 

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#250] opened 2017-10-08 01:13 UTC
On the Admin management page for Destination there is a hidden column but there is actually no way to "hide" a destination. There is only a way to delete a destination.

Either the hidden column should be removed or there should be functionality to hide a destination, not allowing non-admin users to interact with that destination

![screen shot 2017-10-07 at 9 10 07 pm](https://user-images.githubusercontent.com/17053096/31313038-2d89df3a-aba4-11e7-9d9e-ec48787485ba.png)

![screen shot 2017-10-07 at 9 10 12 pm](https://user-images.githubusercontent.com/17053096/31313040-30b8047a-aba4-11e7-8616-fb7b7ba5e1e8.png)

**Comment by engerm** [comment] 2017-10-08 01:21
Found it...

```
./nomad/app/admin/views.py:250:@admin_bp.route('/admin/destinations/<uuid>/hide')
./nomad/app/admin/views.py:264:@admin_bp.route('/admin/destinations/<uuid>/unhide')
```

**Comment by iandees** [comment] 2017-10-08 04:04
Dupe of #208.

**Closed by iandees** 2017-10-08 04:04 UTC
