### ISSUE TITLE
Feedback: nomad site should have a feedback/Contact Us option

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#93] opened 2017-07-30 12:57 UTC
The nomad site should has a feedback/Contact Us feature where a user (driver, passenger, campaign) can contact Nomad volunteers to address any concerns or issues that user is having.

Example issues:
- delete me account and purge all data
- ride didn't show
- general usability feedback about nomad

**Comment by engerm** [comment] 2017-10-03 23:30
this is related to #210 get Intercom working with nomad for support #210

**Comment by schloo** [comment] 2017-10-08 13:11
I also added some space on it for the About/Home page... whoever figures out Intercom, is there a module we can plop there?

**Comment by iandees** [comment] 2017-10-09 02:35
I'm going to close this as a dupe of #210.

**Closed by iandees** 2017-10-09 02:35 UTC
Labels: priority
