### ISSUE TITLE
Can't log out, returned to homepage - Safari on Mac

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#437] opened 2017-10-16 15:31 UTC
Steps
1. Open nomad-staging.ragtag.org already logged in from previous session
2. Try to log out

Happened from homepage, from My Carpools page, from find a ride map page

**Comment by iandees** [comment] 2017-10-16 15:32
Can you give some more details here?

**Comment by iandees** [comment] 2017-10-16 15:32
How did you logout? What page were you on?

**Comment by iandees** [comment] 2017-10-17 12:12
I'm going to close this because I can't figure out what the issue is. Logging out works for me on Safari from all the pages I've tested it on.

**Closed by iandees** 2017-10-17 12:12 UTC
Labels: bug
