### ISSUE TITLE
need to update error message styling on profile page

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#279] opened 2017-10-08 18:53 UTC
![screenshot from 2017-10-08 14-53-30](https://user-images.githubusercontent.com/1630603/31319853-80b7e564-ac38-11e7-9b40-e53dbe720354.png)

**Comment by iandees** [comment] 2017-10-08 19:56
Dupe of #258.

**Closed by iandees** 2017-10-08 19:56 UTC
Labels: bug, qa requested
