### ISSUE TITLE
need to update error message styling on /carpools/new page

### ISSUE THREAD

**Issue by mjlepouttre** [RagtagOpen/nomad#280] opened 2017-10-08 18:59 UTC
![screenshot from 2017-10-08 14-58-46](https://user-images.githubusercontent.com/1630603/31319883-43c26660-ac39-11e7-9686-676459933895.png)

**Comment by iandees** [comment] 2017-10-08 19:55
Dupe of #258.

**Closed by iandees** 2017-10-08 19:55 UTC
Labels: bug, qa requested
