### ISSUE TITLE
web template: carpools page not very scrollable

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#363] opened 2017-10-14 03:09 UTC
the rides doesn't show the full details for the last carpool if user has to scroll down

<img width="1366" alt="screen shot 2017-10-13 at 11 08 22 pm" src="https://user-images.githubusercontent.com/17053096/31572076-992f36ec-b06b-11e7-8792-8aaceee29dda.png">

**Comment by dryan** [comment] 2018-08-16 23:06
Dupe of #424

**Closed by dryan** 2018-08-16 23:06 UTC
Labels: bug, starter, web template
