### ISSUE TITLE
Users can make two accounts, make duplicate requests

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#217] opened 2017-09-30 20:54 UTC
You can create an account with Google and then another with FB. I guarantee the grandmas using this will forget which they did, and do the other the next time they use it, then be confused when their rides or carpools they've set up are missing.
Then they'll request a spot on a carpool they've already applied to with a FB account with a second Google account, and vice versa.
Nomad needs to recognize when a FB account uses the same email as a Google-based account, and link them or sync them if possible

**Comment by engerm** [comment] 2017-09-30 21:39
Related to email addresses must be unique #186

**Comment by iandees** [comment] 2017-10-09 01:41
Yea, going to close this as dupe of #186.

**Closed by iandees** 2017-10-09 01:41 UTC
