### ISSUE TITLE
Have a Spanish option for the site

### ISSUE THREAD

**Issue by flynnwastaken** [RagtagOpen/nomad#466] opened 2017-10-19 02:07 UTC
Same site, same database, everything in Spanish

Could be a different URL. Maybe better if it's the same URL, just with a toggle on the homepage?

**Comment by iandees** [comment] 2017-10-19 02:10
This step in the "Flask Mega Tutorial" gives a pretty decent idea of what it'll take to support internationalization/translations: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiv-i18n-and-l10n

**Comment by engerm** [comment] 2017-10-19 03:47
This is a dupe of #318

**Closed** 2017-10-19 03:48 UTC
Labels: enhancement
