### ISSUE TITLE
Ride requested email previews throwing 500 server error

### ISSUE THREAD

**Issue by kcaffall** [RagtagOpen/nomad#608] opened 2018-08-17 16:50 UTC
Related to #604 
Ride requested email previews throwing 500 server error
https://nomad-staging.ragtag.org/admin/emailpreview/ride_requested

There are destinations, ride requests, etc. #604 was caused by a new install and no carpools. Is there some other config required for this specific email?

**Comment by kdechant** [comment] 2018-08-20 07:55
A look at the Git history shows that a new variable was added to the email template in #516. The email template preview feature in the admin was never updated to pass this variable into the template. @kielni wondering if you have some insight here.

**Comment by iandees** [comment] 2018-08-20 15:27
Sentry error: https://sentry.ragtag.org/ragtag/nomad-staging/issues/86/

**Comment by jillh510** [comment] 2018-08-20 21:07
@iandees, will your fix also take care of #604?

**Comment by iandees** [comment] 2018-08-20 21:13
Yes. I would say that #604 is a dupe of this and should be closed.

**Closed** 2018-08-20 22:17 UTC
Labels: priority
